### ISSUE TITLE
CMC client may throw unchecked exception  where a checked exception should be expected

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/ca-cmc#7]
Exception handling should be fixed to ensure that the CMC client does not provide an unchecked exception unless the error is caused by internal misconfiguration or a programming error in its use.

All errors caused by a bad or unserviceable request should result in a checked exception.

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/swedenconnect/ca-cmc/pull/10.
